### ISSUE TITLE
BUG: check for just one `#` in PR number

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/action-check-changelogfile#12]
A changelog entry ending with `[##2927]` should have failed the test. Easy fix, I just don't have time right now to fix it, therefore I open this reminder.

Another example that should be fixed: `[#2910] [#2932]`, it should be `[#2910, #2932]`

**Comment by pllim** [comment]
Some regex-fu is needed here, I think:

https://github.com/scientific-python/action-check-changelogfile/blob/064f2005176e1622e7c2bd9776140406609097d1/rst_parser.py#L11-L13

And then also maybe new tests to be added to https://github.com/scientific-python/action-check-changelogfile/blob/main/test_rst_parser.py

Even so, only the actual parsing logic would be tested, not the action as a whole, so maybe extra testing downstream is needed too, if you want to be extra safe.
